//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Functions.JFK.FENY
{
    using System.Data.Entity;
    using Edis.Functions.Base;
    using Edis.ViewModels.JFK.FENY;
    using Edis.Entities.JFK.FENY;
    using System;
    using System.Linq;

    public class FelfuggesztesFunctions : KonasoftBVFonixFunctionsBase<FelfuggesztesViewModel, Felfuggesztes>, IFelfuggesztesFunctions
    {

        public DbSet<Felfuggesztes> Table => KonasoftBVFonixContext.Felfuggesztesek;

        public void CreateFelfuggesztes(DateTime kezdete, int okaCimkeId, int fegyelmiUgyId)
        {
            Table.Add(new Felfuggesztes()
            {
                Kezdete = kezdete,
                OkaCimkeId = okaCimkeId,
                FegyelmiUgyId = fegyelmiUgyId

            });
            KonasoftBVFonixContext.SaveChanges();
        }
        public int GetFelfuggesztettNapokSzama(int fegyelmiUgyId, DateTime? minDatum)
        {
            var datum = minDatum.HasValue ? minDatum.Value : DateTime.MinValue;
            var felfuggesztesek = Table.Where(w => w.Kezdete > datum && w.FegyelmiUgyId == fegyelmiUgyId && w.Vege != null).ToList();
            var napokSzama = 0;

            foreach (var felfuggesztes in felfuggesztesek)
            {
                napokSzama += (int)Math.Ceiling((felfuggesztes.Vege.Value - felfuggesztes.Kezdete).TotalDays) + 1;
            }

            return napokSzama;
        }
    }
}
