//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Functions.JFK.FENY
{
    using Edis.Functions.Base;
    using Edis.ViewModels.JFK.FENY;
    using Edis.Entities.JFK.FENY;
    using System;

    public interface IFelfuggesztesFunctions : IDbSetBase<Felfuggesztes>, IKonasoftBVFonixFunctionsBase<FelfuggesztesViewModel, Felfuggesztes>
    {
        void CreateFelfuggesztes(DateTime kezdete, int okaCimkeId, int fegyelmiUgyId);
        int GetFelfuggesztettNapokSzama(int fegyelmiUgyId, DateTime? minDatum);
    }
}
