//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Entities.Common
{
    using System;
    using Edis.Entities.Base;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    [Table("dbo.FunkcioEngedelyezes")]
    public class FunkcioEngedelyezes : KeziJavitoEntity
    {
        
		[Column("FunkcioAzonosito")]
		public string FunkcioAzonosito { get; set; }

        [Column("FunkcioParameter")]
        public string FunkcioParameter { get; set; }

        [Column("FunkcioEngedelyezett")]
		public bool FunkcioEngedelyezett { get; set; }


    }
}
