//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Functions.JFK.FENY
{
    using Edis.Functions.Base;
    using Edis.ViewModels.JFK.FENY;
    using Edis.Entities.JFK.FENY;
    using System.Collections.Generic;
    using Edis.ViewModels.JFK;
    using Edis.ViewModels;

    public interface IEsemenyekFunctions : IDbSetBase<Esemenyek>, IKonasoftBVFonixFunctionsBase<EsemenyViewModel, Esemenyek>
    {
        List<KSelect2ItemModel> GetFogvatartottak();
        List<KSelect2ItemModel> FindFogvatartottakForSelect(string pattern, int? intezetId);
        List<EsemenyViewModel> GetEsemenyekByIntezetId(int intezetId);
        List<int> CreateEsemeny(EsemenyMentesViewModel model);
        List<int> ModifyEsemeny(EsemenyMentesViewModel model);
        EsemenyMentesViewModel GetEsemeny(int? esemenyId);
        EsemenyViewModel GetEsemenyById(int id);

        EsemenyReszletekViewModel GetEsemenyReszletek(int esemenyId);
        List<EsemenyListItemViewModel> GetEsemenyek();
    }
}
