//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Functions.JFK.FENY
{
    using Edis.Functions.Base;
    using Edis.Entities.JFK.FENY;
    using Edis.ViewModels.JFK.FENY;
    using System.Collections.Generic;

    public interface IIktatottDokumentumokFunctions : IDbSetBase<IktatottDokumentumok>, IKonasoftBVFonixFunctionsBase<IktatottDokumentumokViewModel, IktatottDokumentumok>
    {
        int CreateNyomtatvany(IktatottDokumentumokViewModel model);
        //IktatottDokumentumokViewModel GetLastIktatottNyomtatvany(int fegyelmiUgyId);
        //List<IktatottDokumentumokViewModel> GetIktatatottNyomtatvanyok(int fegyelmiUgyId);
        List<IktatottDokumentumokViewModel> GetIktatottDokumentumokTeljes(int fegyelmiUgyId);

        string SerializeIktatottNyomtatvanyAdat(object model);
        T DeserializeIktatottNyomtatvanyAdat<T>(string jsonData);
    }
}
