//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Functions.JFK.FENY
{
    using Edis.Functions.Base;
    using Edis.Entities.JFK.FENY;
    using Edis.ViewModels.JFK.FENY;
    using System.Collections.Generic;

    public interface IIktatottNyomtatvanyokFunctions : IDbSetBase<IktatottNyomtatvanyok>, IKonasoftBVFonixFunctionsBase<IktatottNyomtatvanyokViewModel, IktatottNyomtatvanyok>
    {
        int CreateNyomtatvany(IktatottNyomtatvanyokViewModel model);
        IktatottNyomtatvanyokViewModel GetLastIktatottNyomtatvany(int fegyelmiUgyId);
        List<IktatottNyomtatvanyokViewModel> GetIktatatottNyomtatvanyok(int fegyelmiUgyId);
        List<IktatottNyomtatvanyokViewModel> GetIktatottNyomtatvanyokTeljes(int fegyelmiUgyId);
    }
}
