//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Functions.JFK.FENY
{
    using System.Data.Entity;
    using Edis.Functions.Base;
    using Edis.Entities.JFK.FENY;
    using Edis.ViewModels.JFK.FENY;
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using Edis.Diagnostics;

    public class IktatottNyomtatvanyokFunctions : KonasoftBVFonixFunctionsBase<IktatottNyomtatvanyokViewModel, IktatottNyomtatvanyok>, IIktatottNyomtatvanyokFunctions
    {
		public DbSet<IktatottNyomtatvanyok> Table => KonasoftBVFonixContext.IktatottNyomtatvanyok;

        public int CreateNyomtatvany(IktatottNyomtatvanyokViewModel model) {

            bool siker = false;
            int result = 1;

            while (!siker)
            {
                try
                {
                    int alszam = Table.AsNoTracking().Where(x => x.FegyelmiUgyId == model.FegyelmiUgyId).Count();
                    model.Alszam = (byte)++alszam;
                    result = Create(model);
                    siker = true;
                }
                catch (InvalidOperationException ex)
                {
                    Log.Info($"{model.FegyelmiUgyId} fegyelmi ügyhöz {model.Alszam} alszám már létezik az adatbázisban. Újrapróbálkozás...");
                }
            }

            return result;
        }

        public IktatottNyomtatvanyokViewModel GetLastIktatottNyomtatvany(int fegyelmiUgyId)
        {
            var iktatas = Table.AsNoTracking().Where(x => x.FegyelmiUgyId == fegyelmiUgyId).OrderByDescending(x => x.Alszam).FirstOrDefault();
            return (IktatottNyomtatvanyokViewModel)iktatas;
        }

        public List<IktatottNyomtatvanyokViewModel> GetIktatatottNyomtatvanyok(int fegyelmiUgyId)
        {
            var iktatasok = Table.AsNoTracking().Where(x => x.FegyelmiUgyId == fegyelmiUgyId).ToList().Select(x => (IktatottNyomtatvanyokViewModel)x).ToList();
            return iktatasok;
        }

        public List<IktatottNyomtatvanyokViewModel> GetIktatottNyomtatvanyokTeljes(int fegyelmiUgyId)
        {
            var iktatasok = Table
                .Include(x => x.Dokumentum)
                .Include(x => x.RogzitoSzemely)
                .Include(x => x.ModositoSzemely)
                .AsNoTracking().Where(x => x.FegyelmiUgyId == fegyelmiUgyId).ToList().Select(x => (IktatottNyomtatvanyokViewModel)x).ToList();
            return iktatasok;
        }
    }
}
