//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Functions.JFK.FENY
{
    using System.Data.Entity;
    using Edis.Functions.Base;
    using Edis.Entities.JFK.FENY;
    using Edis.ViewModels.JFK.FENY;
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Edis.ViewModels.Common;

    public class IktatottDokumentumokFunctions : KonasoftBVFonixFunctionsBase<IktatottDokumentumokViewModel, IktatottDokumentumok>, IIktatottDokumentumokFunctions
    {
        public DbSet<IktatottDokumentumok> Table => KonasoftBVFonixContext.IktatottDokumentumok;

        public int CreateNyomtatvany(IktatottDokumentumokViewModel model) 
        {
            int result = 0;

            KonasoftBVFonixContext.DisableToroltFlFilter(t => t.IktatottDokumentumok);

            try
            {
                int alszam = Table.AsNoTracking().Where(x => x.FegyelmiUgyId == model.FegyelmiUgyId).Select(x => x.Alszam).DefaultIfEmpty((byte)0).Max();
                model.Alszam = (byte)(alszam + 1);
                result = Create(model);
                model.Id = result;
                result = 1;
            }
            finally
            {
                KonasoftBVFonixContext.EnableToroltFlFilter(t => t.IktatottDokumentumok);
            }

            return result;
        }

        //public IktatottDokumentumokViewModel GetLastIktatottNyomtatvany(int fegyelmiUgyId)
        //{
        //    var iktatas = Table.AsNoTracking().Where(x => x.FegyelmiUgyId == fegyelmiUgyId).OrderByDescending(x => x.Alszam).FirstOrDefault();
        //    return (IktatottDokumentumokViewModel)iktatas;
        //}

        //public List<IktatottDokumentumokViewModel> GetIktatatottNyomtatvanyok(int fegyelmiUgyId)
        //{
        //    var iktatasok = Table.AsNoTracking().Where(x => x.FegyelmiUgyId == fegyelmiUgyId).OrderByDescending(x => x.Alszam).ToList().Select(x => (IktatottDokumentumokViewModel)x).ToList();
        //    return iktatasok;
        //}

        public List<IktatottDokumentumokViewModel> GetIktatottDokumentumokTeljes(int fegyelmiUgyId)
        {
            var iktatasok = Table
                .Include(x => x.DokumentumTipus)
                //.Include(x => x.RogzitoSzemely)
                //.Include(x => x.ModositoSzemely)
                //.Include(x => x.Naplo)
                .AsNoTracking().Where(x => x.FegyelmiUgyId == fegyelmiUgyId)
                .Select(t => new { t.Id, t.RogzitoSzemelyId, t.LetrehozasDatuma, t.KeziJavitasAzonosito, t.FegyelmiUgyId, t.DokumentumTipusCimkeId, t.Alszam, t.AktivFl, t.DokumentumTipus, t.ModositoSzemelyId, t.ModositasDatuma, t.NaploId })
                .ToList()
                .Select(x => new IktatottDokumentumokViewModel { Id = x.Id, RogzitoIntezetId = x.RogzitoSzemelyId, LetrehozasDatuma = x.LetrehozasDatuma, KeziJavitasAzonosito = x.KeziJavitasAzonosito, FegyelmiUgyId = x.FegyelmiUgyId, DokumentumTipusCimkeId = x.DokumentumTipusCimkeId, Alszam = x.Alszam, AktivFl = x.AktivFl, DokumentumTipus = (CimkeModel)x.DokumentumTipus, ModositoSzemelyId = x.ModositoSzemelyId, ModositasDatuma = x.ModositasDatuma, NaploId = x.NaploId })
                .ToList();
            return iktatasok;
        }

        public string SerializeIktatottNyomtatvanyAdat(object model)
        {
            return JsonConvert.SerializeObject(model);
        }

        public T DeserializeIktatottNyomtatvanyAdat<T>(string jsonData)
        {
            return JsonConvert.DeserializeObject<T>(jsonData);
        }
       
    }
}
