//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Entities.JFK.FENY
{
    using System;
    using Edis.Entities.Base;
    using System.ComponentModel.DataAnnotations.Schema;
    using Edis.Entities.Common;
    using Edis.Entities.Fany;

    [Table("Fegyelmi.Resztvevok")]
    public class EsemenyResztvevo : KeziJavitoEntity
    {
		[Column("FogvatartottId")]
		public int? FogvatartottId { get; set; }
        
        [Column("ErintettsegFokaCimkeId")]
		public int ErintettsegFokaCimkeId { get; set; }

		[Column("EsemenyId")]
		public int EsemenyId { get; set; }

        [Column("AllomanyiSzemelyId")]
        public int? AllomanyiSzemelyId { get; set; }

        //[Column("Bizonyitek")]
        //public string Bizonyitek { get; set; }

        [ForeignKey(nameof(FogvatartottId))]
        public virtual FogvatartottListaItemFegyelmiView Fogvatartott { get; set; }

        [ForeignKey(nameof(AllomanyiSzemelyId))]
        public virtual Szemelyzet AllomanyiSzemely { get; set; }

        [ForeignKey(nameof(ErintettsegFokaCimkeId))]
        public virtual Cimke ErintettsegFoka { get; set; }

    }
}
