//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Entities.JFK.FENY
{
    using System;
    using Edis.Entities.Base;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    [Table("Fegyelmi.Felfuggesztesek")]
    public class Felfuggesztes : KeziJavitoEntity
    {
        
		[Column("Kezdete")]
		public DateTime Kezdete { get; set; }

		[Column("Vege")]
		public DateTime? Vege { get; set; }

		[Column("OkaCimkeId")]
		public int OkaCimkeId { get; set; }

		[Column("FegyelmiUgyId")]
		public int FegyelmiUgyId { get; set; }


    }
}
