//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.Entities.JFK.FENY
{
    using System;
    using Edis.Entities.Base;
    using System.ComponentModel.DataAnnotations.Schema;
    using Edis.Entities.Common;
    using Edis.Entities.Fany;
    using Edis.Entities.Attributes;

    [Table("Fegyelmi.Naplo")]
    public class Naplo : KeziJavitoEntity
    {
        
		[Column("FegyelmiUgyId")]
		public int FegyelmiUgyId { get; set; }

        [Column("JegyzokonyvVezetoSzemelyId")]
        public int? JegyzokonyvVezetoSzemelyId { get; set; }

        [ForeignKey(nameof(JegyzokonyvVezetoSzemelyId))]
        public virtual Szemelyzet JegyzokonyvVezetoSzemely { get; set; }

        [Column("FogvatartottId")]
		public int? FogvatartottId { get; set; }
        [ForeignKey(nameof(FogvatartottId))]

        public virtual FogvatartottListaItemFegyelmiView Fogvatartott { get; set; }
        [Column("FogvatartottNyelve")]
		public string FogvatartottNyelve { get; set; }

        [Column("JegyzokonyvLezarasDatuma")]
        public DateTime? JegyzokonyvLezarasDatuma { get; set; }

        [Column("TipusCimkeId")]
		public int TipusCimkeId { get; set; }

        [ForeignKey(nameof(TipusCimkeId))]
        public virtual Cimke TipusCimke { get; set; }

        [Column("AlairtaFl")]
        public bool? AlairtaFl { get; set; }

        [Column("InaktivFl")]
        public bool? InaktivFl { get; set; }

        [Column("TovabbiJelenlevok")]
        [SkipFirstUpperCaseConversion]
        public string TovabbiJelenlevok { get; set; }

        [Column("KihallgatasIntezetId")]
        public int? KihallgatasIntezetId { get; set; }

        [ForeignKey(nameof(KihallgatasIntezetId))]
        public virtual Intezet KihallgatasIntezet { get; set; }

        [Column("KihallgatasHelye")]
        public string KihallgatasHelye { get; set; }

        [Column("Jegyzokonyv")]
        public string JegyzokonyvTartalma { get; set; }

        [Column("MeghallgatoSzemelyId")]
        public int? MeghallgatoSzemelyId { get; set; }

        [ForeignKey(nameof(MeghallgatoSzemelyId))]
        public virtual Szemelyzet MeghallgatoSzemely { get; set; }
        [Column("DonteshozoSzemelyId")]
        public int? DonteshozoSzemelyId { get; set; }

        [ForeignKey(nameof(DonteshozoSzemelyId))]
        public virtual Szemelyzet DonteshozoSzemely { get; set; }

        [Column("KivizsgaloSzemelyId")]
        public int? KivizsgaloSzemelyId { get; set; }

        [ForeignKey(nameof(KivizsgaloSzemelyId))]
        public virtual Szemelyzet KivizsgaloSzemely { get; set; }

        [Column("Hatarido")]
        public DateTime? Hatarido { get; set; }

        [Column("FogvatartottElfogadta")]
        public bool? IsFogvatartottElfogadta { get; set; }

        [Column("FegyelmiVetsegTipusaCimkeId")]
        public int? FegyelmiVetsegTipusaCimkeId { get; set; }

        [ForeignKey(nameof(FegyelmiVetsegTipusaCimkeId))]
        public virtual Cimke FegyelmiVetsegTipusaCimke { get; set; }

        [Column("ReintegraciosReszlegId")]
        public int? ReintegraciosReszlegId { get; set; }

        [ForeignKey(nameof(ReintegraciosReszlegId))]
        public virtual NevelesiCsoport ReintegraciosReszleg { get; set; }

        [Column("FenyitesKiszabasDatuma")]
        public DateTime? FenyitesKiszabasDatuma { get; set; }

        [ForeignKey(nameof(SzemelyiAllomanyiTanuSzemelyId))]
        public virtual Szemelyzet SzemelyiAllomanyiTanuSzemely { get; set; }

        [Column("SzemelyiAllomanyiTanuSzemelyId")]
        public int? SzemelyiAllomanyiTanuSzemelyId { get; set; }

        [Column("HatarozatHozoJogkoreCimkeId")]
        public int? HatarozatHozoJogkoreCimkeId { get; set; }

        [ForeignKey(nameof(HatarozatHozoJogkoreCimkeId))]
        public virtual Cimke HatarozatHozoJogkoreCimke { get; set; }

        [Column("ElsofokuTargyalasIdopontja")]
        public DateTime? ElsofokuTargyalasIdopontja { get; set; }
        
        [Column("VisszakuldesOkaCimkeId")]
        public int? VisszakuldesOkaCimkeId { get; set; }
        [ForeignKey(nameof(VisszakuldesOkaCimkeId))]
        public virtual Cimke VisszakuldesOkaCimke { get; set; }

        [Column("EgyebAdatokJson")]
        public string EgyebAdatokJson { get; set; }
        [Column("Vegleges")]
        public bool? Vegleges { get; set; } 
        [Column("MasodfokuTargyalasIdopontja")]
        public DateTime? MasodfokuTargyalasIdopontja { get; set; }

        [Column("FenyitesTipusCimkeId")]
        public int? FenyitesTipusCimkeId { get; set; }
        [ForeignKey(nameof(FenyitesTipusCimkeId))]
        public virtual Cimke FenyitesTipusCimke { get; set; }

        [Column("FenyitesHossza")]
        public int? FenyitesHossza { get; set; }

        [Column("FenyitesHosszaMennyisegiEgysegCimkeId")]
        public int? FenyitesHosszaMennyisegiEgysegCimkeId { get; set; }

        [ForeignKey(nameof(FenyitesHosszaMennyisegiEgysegCimkeId))]
        public virtual Cimke FenyitesHosszaMennyisegiEgysegCimke { get; set; }

        [Column("KietkezesCsokkentes")]        
        public byte? KietkezesCsokkentes { get; set; }        

        [Column("VetsegRendeletSzerintCimkeId")]
        public int? VetsegRendeletSzerintCimkeId { get; set; }
        [ForeignKey(nameof(VetsegRendeletSzerintCimkeId))]
        public virtual Cimke VetsegRendeletSzerintCimke { get; set; }
        [Column("TorvenyszekId")]
        public int? TorvenyszekId { get; set; }
        [Column("TitulusCimkeId")]
        public int? TitulusCimkeId { get; set; }
        [ForeignKey(nameof(TitulusCimkeId))]
        public virtual Cimke TitulusCimke { get; set; }
        [Column("VedoElerhetosege")]
        public string VedoElerhetosege { get; set; }
        [Column("VedoNeve")]
        public string VedoNeve { get; set; }
        [Column("VedoCime")]
        public string VedoCime { get; set; }
        
       [Column("FelfuggesztesOkaCimkeId")]
        public int? FelfuggesztesOkaCimkeId { get; set; }

        [Column("InkognitoFl")]
        public bool? InkognitoFl { get; set; }

        public int? TajekoztatastNyujtoId { get; set; }

        public string Tajekoztatott { get; set; }

        public string Telefonszam { get; set; }

        public DateTime? TajekoztatasIdeje { get; set; }

        public string TajekoztatasSikertelensegenekOka { get; set; }
       
        [Column("Szembesitett1FogvatartottId")]
        public int? Szembesitett1FogvatartottId { get; set; }

        [Column("Szembesitett2FogvatartottId")]
        public int? Szembesitett2FogvatartottId { get; set; }
               
        public int? MegszuntetesOkaCimkeId { get; set; }
        public string ElozmenyUgyAzonosito { get; set; }
        public int? SertettId { get; set; }
        public string SertettKepviseloje { get; set; }
        public string EljarasAlaVontKepviseloje { get; set; }
        public bool? IsHelybenhagyasFl { get; set; }
        public bool? Visszautasitva { get; set; }
        
        [Column("Indoklas")]
        public string Indoklas { get; set; }

        public bool? GaranciaTeljesultFl { get; set; }

        [Column("KozvetitoiSikeresFL")]
        public bool? KozvetitoiSikeresFL { get; set; }

        [Column("ElkulonitesOka")]
        public string ElkulonitesOka { get; set; }

        [Column("ElkulonitesRendelkezesek")]
        public string ElkulonitesRendelkezesek { get; set; }
        
        [Column("ElkulonitesElrendelesIdeje")]
        public DateTime? ElkulonitesElrendelesIdeje { get; set; }

        [Column("ElkulonitesMegszuntetesenekIdeje")]
        public DateTime? ElkulonitesMegszuntetesenekIdeje { get; set; }

        [Column("ElkulonitesFelulvizsgalvaFL")]
        public bool? ElkulonitesFelulvizsgalvaFL { get; set; }
        

        [Column("AutomatikusFl")]
        public bool? AutomatikusFl { get; set; }

        [Column("MaganelzarasVegeDatum")]
        public DateTime? MaganelzarasVegeDatum { get; set; }
    }
}
