import { registerComponent } from '../../utils/vueUtils';

import './kozvetitoiEljaras/_index';
import './fegyelmiElkulonites/_index';
import './Jutalom/_index';

import ReintegraciosTisztDonteseFeddes from './ReintegraciosTisztDonteseFeddes.vue';
import ReintegraciosTisztDonteseKioktatas from './ReintegraciosTisztDonteseKioktatas.vue';
import MasodFokuFegyelmiTargyalasElokeszitese from './MasodFokuFegyelmiTargyalasElokeszitese.vue';
import KirendeltVedoKerese from './KirendeltVedoKerese.vue';
import MeghatalmazottVedoKerese from './MeghatalmazottVedoKerese.vue';
import HataridoModositas from './HataridoModositas.vue';
import Felfuggesztes from './Felfuggesztes.vue';
import VedoTelefonosTajekoztatasa from './VedoTelefonosTajekoztatasa.vue';
import FelfuggesztesMegszuntetes from './FelfuggesztesMegszuntetes.vue';
import SzakteruletiVelemenyKerese from './SzakteruletiVelemenyKerese.vue';
import MasodFokuTargyalasiJegyzokonyv from './MasodFokuTargyalasiJegyzokonyv.vue';
import HatarozatRogziteseMasodFoku from './HatarozatRogziteseMasodFoku.vue';
import SzembesitesiJegyzokonyv from './SzembesitesiJegyzokonyv.vue';
import MaganelzarasMegkezdesenekRogzitese from './MaganelzarasMegkezdesenekRogzitese.vue';
import FenyitesVegrehajthatatlannaTetele from './FenyitesVegrehajthatatlannaTetele.vue';
import MaganelzarasIdeiglenesenEllenjavallt from './MaganelzarasIdeiglenesenEllenjavallt.vue';
import MaganelzarasMegszakitasa from './MaganelzarasMegszakitasa.vue';
import MaganelzarasVegrehajtva from './MaganelzarasVegrehajtva.vue';
import HataridoTullepesMiattiMegszuntetes from './HataridoTullepesMiattiMegszuntetes.vue';
import Csatolmanyok from '../controls/Csatolmanyok.vue';
import BuntetoFeljelentesRogzitese from './BuntetoFeljelentesRogzitese.vue';
import JavaslatFelfuggesztesre from './JavaslatFelfuggesztesre.vue';
import JavaslatUjHataridore from './JavaslatUjHataridore.vue';
import SzabadszovegesNaplobejegyzesRogzitese from './SzabadszovegesNaplobejegyzesRogzitese.vue';
import Rendszerbeallitasok from './site/Rendszerbeallitasok.vue';
import MaganelzarasElrendelese from './MaganelzarasElrendelese.vue';
import KivizsgaloModositasa from './KivizsgaloModositasa.vue';
import JutalomEloterjesztes from './JutalomEloterjesztes.vue';
import HatalyonKivulHelyezes from './HatalyonKivulHelyezes.vue';

registerComponent(ReintegraciosTisztDonteseFeddes);
registerComponent(ReintegraciosTisztDonteseKioktatas);
registerComponent(MasodFokuFegyelmiTargyalasElokeszitese);
registerComponent(KirendeltVedoKerese);
registerComponent(MeghatalmazottVedoKerese);
registerComponent(HataridoModositas);
registerComponent(FelfuggesztesMegszuntetes);
registerComponent(Felfuggesztes);
registerComponent(VedoTelefonosTajekoztatasa);
registerComponent(SzakteruletiVelemenyKerese);
registerComponent(MasodFokuTargyalasiJegyzokonyv);
registerComponent(HatarozatRogziteseMasodFoku);
registerComponent(SzembesitesiJegyzokonyv);
registerComponent(MaganelzarasMegkezdesenekRogzitese);
registerComponent(FenyitesVegrehajthatatlannaTetele);
registerComponent(MaganelzarasIdeiglenesenEllenjavallt);
registerComponent(MaganelzarasMegszakitasa);
registerComponent(MaganelzarasVegrehajtva);
registerComponent(Csatolmanyok);
registerComponent(HataridoTullepesMiattiMegszuntetes);
registerComponent(BuntetoFeljelentesRogzitese);
registerComponent(JavaslatFelfuggesztesre);
registerComponent(JavaslatUjHataridore);
registerComponent(SzabadszovegesNaplobejegyzesRogzitese);
registerComponent(Rendszerbeallitasok);
registerComponent(MaganelzarasElrendelese);
registerComponent(KivizsgaloModositasa);
registerComponent(JutalomEloterjesztes);
registerComponent(HatalyonKivulHelyezes);
