//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class FegyelmiLapViewModel
    {
        public string UgySzama { get; set; }
        public string Nev { get; set; }
        public string Azonosito { get; set; }
        public string SzuletesiHely { get; set; }
        public string SzuletesiIdo { get; set; }
        public string AnyjaNeve { get; set; }
        public string FogvElhelyezese { get; set; }
        public string TartozkodasFokaJogcime { get; set; }
        public string AktualisSzabadulasiIdo { get; set; }
        public int EsemenySorszama { get; set; }
        public string EsemenyEszlelese { get; set; }
        public string EsemenytEszlelte { get; set; }
        public string EsemenyLeirasa { get; set; }
        public string IntezetNev { get; set; }
        public string Telepules { get; set; }
        public string Iktatoszam { get; set; }
    }
}
