//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class KozvetitoiEljarasonReszvetelNyomtatasViewModel
    {
        public string IntezetNev { get; set; }
        public string Iktatoszam { get; set; }
        public string UgySzam { get; set; }
        public string Fogvatartott { get; set; }
        public string FogvAzon { get; set; }
        public string SzulDatum { get; set; }
        public string ErintettsegFoka { get; set; }
        public string Javaslat { get; set; }
        public string ReintegraciosTiszt { get; set; }
        public string Telepules { get; set; }
        public string IktatasDatum { get; set; }
    }
}
