//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class MasodfokuFegyelmiHatarozatViewModel
    {
        public int FegyelmiUgyId { get; set; }
        public string IntezetNev { get; set; }
        public string Iktatoszam { get; set; }

        public string Fogvatartott { get; set; }

        public string FogvAzon { get; set; }

        public string FogvatartottAnyjaNeve { get; set; }

        public string FogvatartottSzulHelye { get; set; }

        public string FogvatartottSzulIdeje { get; set; }

        public string FogvSzabadul { get; set; }

        public string BvFok { get; set; }

        public string IndoklasText { get; set; }

        public string HatarozatHely { get; set; }

        public string HatarozatDatum { get; set; }

        public string HatarozathozoNev { get; set; }

        public string HatarozathozoRang { get; set; }

        public string HatarozathozoTitulus { get; set; }

        public string HatarozathozoSzam { get; set; }

        public string FegyelmiUgy { get; set; }

        public string FenyIdotart { get; set; }

        public string KietkezesCsokkentes { get; set; }

        public string FenyTipus { get; set; }

        public string FegyVetseg { get; set; }
        public string Elhelyezes { get; set; }
        public string Torvenyszek { get; set; }
        public string TartozkodasFokaJogcime { get; set; }

    }
}
