//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class MeghatalmazottVedoKirendeleseViewModel
    {
        public int FegyelmiUgyId { get; set; }
        public string IntezetNev { get; set; }
        public string Iktatoszam { get; set; }
        public string UgySzam { get; set; }
        public string Nev { get; set; }
        public string FogvAzon { get; set; }
        public string AnyjaNeve { get; set; }
        public string SzulDatum { get; set; }
        public string NyomtatoSzemely { get; set; }
        public string ElsofokuTargyalasIdopont { get; set; }
        public string MasodfokuTargyalasIdopont { get; set; }
        public string IntezetCime { get; set; }
        public string UrAsszony { get; set; }
        public string VedoNeve { get; set; }
        public string VedoCime { get; set; }
        public string VedoElerhetosege { get; set; }

    }
}
