//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{

    public class VedoTelefonosTajekoztatasaViewModel
    {
        public int FegyelmiUgyId { get; set; }
        public string IntezetNev { get; set; }
        public string Iktatoszam { get; set; }
        public string UgySzam { get; set; }
        public string Nev { get; set; }
        public string FogvAzon { get; set; }
        public string AnyjaNeve { get; set; }
        public string SzulDatum { get; set; }
        public string NyomtatoSzemely { get; set; }
        public string IntezetCime { get; set; }
        public string TajekoztatoSzemelyNev { get; set; }
        public string TajekoztatottSzemelyNev { get; set; }
        public string TajekoztatottSzemelyTel { get; set; }
        public string TajekoztatoIdopontja { get; set; }
        public string TajekoztatoTartalma { get; set; }
        public string SikertelenText { get; set; }
    }
}
