//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    
    
    public class FelfuggesztesViewModel : BaseViewModel
    {
        
		public DateTime Kezdete { get; set; }

		public DateTime? Vege { get; set; }

		public int OkaCimkeId { get; set; }

		public int FegyelmiUgyId { get; set; }

		public static explicit operator FelfuggesztesViewModel(Felfuggesztes item)
		{
			var model = ValueInjecterUtilities.InjectViewModel<Felfuggesztes, FelfuggesztesViewModel>(item);
			return model;
		}

		public static explicit operator Felfuggesztes(FelfuggesztesViewModel model)
		{
			Felfuggesztes entity = new Felfuggesztes();
			entity = ValueInjecterUtilities.InjectViewModel<FelfuggesztesViewModel, Felfuggesztes> (model);

			return entity;
		}
    }
}
