//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;
    using System.IO;

    public class FeltoltesekViewModel : BaseViewModel
    {


        public int? EsemenyId { get; set; }

        public string Url { get; set; }
        
        public int? NaploId { get; set; }

        public string FileName
        {
            get
            {
                return Path.GetFileName(Url);
            }
        }

        public string Extension
        {
            get
            {
                return Path.GetExtension(Url);
            }
        }


        public static explicit operator FeltoltesekViewModel(Feltoltesek item)
        {
            var model = ValueInjecterUtilities.InjectViewModel<Feltoltesek, FeltoltesekViewModel>(item);
            return model;
        }

        public static explicit operator Feltoltesek(FeltoltesekViewModel model)
        {
            Feltoltesek entity = new Feltoltesek();
            entity = ValueInjecterUtilities.InjectViewModel<FeltoltesekViewModel, Feltoltesek>(model);

            return entity;
        }
    }
}
