//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using Edis.ViewModels.Common;
    using Edis.ViewModels.Fany;

    public class IktatottNyomtatvanyokViewModel : BaseViewModel
    {
        
		public int RogzitoSzemelyId { get; set; }

		public int RogzitoIntezetId { get; set; }

		public DateTime ErvenyessegKezd { get; set; }

		public bool ToroltFl { get; set; }

		public DateTime LetrehozasDatuma { get; set; }

		public int? KeziJavitasAzonosito { get; set; }

		public int FegyelmiUgyId { get; set; }

		public int DokumentumId { get; set; }

		public System.Byte Alszam { get; set; }

        public bool AktivFl { get; set; }

        public int? ModositoSzemelyId { get; set; }

        public DateTime? ModositasDatuma { get; set; }

        public NyomtatvanySablonModel Dokumentum { get; set; }
        public SzemelyzetModel RogzitoSzemely { get; set; }
        public SzemelyzetModel ModositoSzemely { get; set; }

		public static explicit operator IktatottNyomtatvanyokViewModel(IktatottNyomtatvanyok item)
		{
			var model = ValueInjecterUtilities.InjectViewModel<IktatottNyomtatvanyok, IktatottNyomtatvanyokViewModel>(item);

            if (item.Dokumentum != null)
            {
                model.Dokumentum = (NyomtatvanySablonModel)item.Dokumentum;
            }

            if (item.RogzitoSzemely != null)
            {
                model.RogzitoSzemely = (SzemelyzetModel)item.RogzitoSzemely;
            }

            if (item.ModositoSzemely != null)
            {
                model.ModositoSzemely = (SzemelyzetModel)item.ModositoSzemely;
            }

            return model;
		}

		public static explicit operator IktatottNyomtatvanyok(IktatottNyomtatvanyokViewModel model)
		{
			IktatottNyomtatvanyok entity = new IktatottNyomtatvanyok();
			entity = ValueInjecterUtilities.InjectViewModel<IktatottNyomtatvanyokViewModel, IktatottNyomtatvanyok> (model);

			return entity;
		}
    }
}
