//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class NaploListaViewmodel : NaploViewModel
    {
        public string JegyzokonyvVezetoSzemely { get; set; }
        public string TipusCimke { get; set; }
        public string KihallgatasIntezet { get; set; }
        public string MeghallgatoSzemely { get; set; }
        public string MeghallgatoSzemelyRendfokozat { get; set; }
        public string SzemelyiAllomanyiTanuSzemely { get; set; }
        public string FegyelmiVetsegTipusaCimke { get; set; }
        public string ReintegraciosReszleg { get; set; }
        public string DonteshozoSzemely { get; set; }
        public string DonteshozoSzemelyRendfokozat { get; set; }
        public string KivizsgaloSzemely { get; set; }
        public string FogvatartottNeve { get; set; }
        public string AktNyilvantartasiSzam { get; set; }
        public string VisszakuldesOkaCimke { get; set; }
        public string SzemelyiAllomanyiTanuRendfokozat { get; set; }
        public string JegyzokonyvVezetoSzemelyRendfokozat { get; set; }
        public string HatarozatHozoJogkoreCimke { get; set; }
        public string FenyitesTipusCimke { get; set; }
        public string VetsegRendeletSzerintCimke { get; set; }
        public string RogzitoSzemelyRendfokozat { get; set; }
        public string Titulus { get; set; }
        public string FelfuggesztesOkaCimke { get; set; }
        public string TajekoztatastNyujto { get; set; }
        public string TajekoztatastNyujtoRendFokozat { get; set; }
        public string Torvenyszek { get; set; }
        public string FenyitesHosszaEsTipusa { get; set; }
        public string Szembesitett1Neve { get; set; }
        public string Szembesitett2Neve { get; set; }
        public string Szembesitett1AzonKod { get; set; }
        public string Szembesitett2AzonKod { get; set; }
        public string SertettNeve { get; set; }
        public string SertettAktNyilvantartasiSzam { get; set; }
        public bool? IsHelybenhagyasFl { get; set; }
        public string Indoklas { get; set; }
        public string MegszuntetesOkaCimke { get; set; }

        public bool? KozvetitoiSikeresFL { get; set; }

        public bool? AutomatikusFl { get; set; }
        public DateTime? MaganelzarasVegeDatum { get; set; }
        public string FogvatartottStatusz { get; set; }
        public int RogzitoSzemelyId { get; set; }
        
        public string Fofelugyelok { get; set; }

        public static explicit operator NaploListaViewmodel(Naplo item)
        {
            var model = ValueInjecterUtilities.InjectViewModel<Naplo, NaploListaViewmodel>(item);
            if (item != null)
            {
                model.RogzitoSzemely = item.RogzitoSzemely?.Nev;
                model.RogzitoSzemelyRendfokozat = item.RogzitoSzemely?.RendfokozatKszId == 0 ? "" : item.RogzitoSzemely?.Rendfokozat?.Nev;
                model.JegyzokonyvVezetoSzemely = item.JegyzokonyvVezetoSzemely?.Nev;
                model.TipusCimke = item.TipusCimke?.Nev;
                model.FegyelmiVetsegTipusaCimke = item.FegyelmiVetsegTipusaCimke?.Nev;
                model.MeghallgatoSzemely = item.MeghallgatoSzemely?.Nev;
                model.KihallgatasIntezet = item.KihallgatasIntezet?.Nev;
                model.DonteshozoSzemely = item.DonteshozoSzemely?.Nev;
                model.DonteshozoSzemelyRendfokozat = item.DonteshozoSzemely?.RendfokozatKszId == 0 ? "" : item.DonteshozoSzemely?.Rendfokozat?.Nev;
                model.KivizsgaloSzemely = item.KivizsgaloSzemely?.Nev;
                model.FogvatartottNeve = item.Fogvatartott?.SzuletesiCsaladiNev + " " + item.Fogvatartott?.SzuletesiUtonev;
                model.AktNyilvantartasiSzam = item.Fogvatartott?.NyilvantartasiAzonosito;
                model.SzemelyiAllomanyiTanuSzemely = item.SzemelyiAllomanyiTanuSzemely?.Nev;
                model.AlairtaFl = item.AlairtaFl;
                model.InaktivFl = item.InaktivFl;
                model.SzemelyiAllomanyiTanuRendfokozat = item.SzemelyiAllomanyiTanuSzemely?.RendfokozatKszId == 0 ? "" : item.SzemelyiAllomanyiTanuSzemely?.Rendfokozat?.Nev;
                model.JegyzokonyvVezetoSzemelyRendfokozat = item.JegyzokonyvVezetoSzemely?.RendfokozatKszId == 0 ? "" : item.JegyzokonyvVezetoSzemely?.Rendfokozat?.Nev;
                model.HatarozatHozoJogkoreCimke = item.HatarozatHozoJogkoreCimke?.Nev;
                model.ElsofokuTargyalasIdopontja = item.ElsofokuTargyalasIdopontja;
                model.VisszakuldesOkaCimke = item.VisszakuldesOkaCimke?.Nev;
                model.ReintegraciosReszleg = item.ReintegraciosReszleg?.Nev;
                model.FenyitesTipusCimke = item.FenyitesTipusCimke?.Nev;
                model.VetsegRendeletSzerintCimke = item.VetsegRendeletSzerintCimke?.Nev;
                model.MeghallgatoSzemelyRendfokozat = item.MeghallgatoSzemely?.RendfokozatKszId == 0 ? "" : item.MeghallgatoSzemely?.Rendfokozat?.Nev;
                model.Titulus = item.TitulusCimke?.Nev;
                model.Indoklas = item.Indoklas;
                model.GaranciaTeljesultFl = item.GaranciaTeljesultFl;
                model.AutomatikusFl = item.AutomatikusFl;
                model.MegszuntetesOkaCimkeId = item.MegszuntetesOkaCimkeId;
                model.MaganelzarasVegeDatum = item.MaganelzarasVegeDatum;
                model.RogzitoSzemelyId = item.RogzitoSzemely?.Id ?? 0;
            }
            return model;
        }

        public static explicit operator Naplo(NaploListaViewmodel model)
        {
            Naplo entity = new Naplo();
            entity = ValueInjecterUtilities.InjectViewModel<NaploListaViewmodel, Naplo>(model);

            return entity;
        }
    }
}
