//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class DontesKozvetitoiEljarasrolModel
    {
        public List<int> FegyelmiUgyIds { get; set; }

        public List<int> NaplobejegyzesIds { get; set; }
        public List<KSelect2ItemModel> KozvetitoOptions { get; set; }
        public string KozvetitoId { get; set; }

        public DateTime MaxDatum { get; set; }
        public DateTime Datum { get; set; }

        public bool IsVisszautasitas { get; set; }
    }
}
