//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class ReintegraciosTisztDontesModel
    {
        
        public List<int> FegyelmiUgyIds { get; set;}
        public List<int> NaplobejegyzesIds { get; set;}
        public List<KSelect2ItemModel> ReintegraciosReszlegOptions { get; set; }
        public List<KSelect2ItemModel> FegyelmiVetsegTipusaOptions { get; set; }
        public DateTime? FenyitesKiszabasIdejeMinDate { get; set; }
        public int? ReintegraciosReszlegId { get; set; }
        public DateTime? FenyitesKiszabasIdeje { get; set; }
        public int? FegyelmiVetsegTipusaCimkeId { get; set; }
        public int DontesTipusId { get; set; }
        public bool IsKarterites { get; set; }
        public bool? IsSzandekosKarokozas { get; set; }
        public bool IsNemVetteTudomasul { get; set; }
        public bool? Vegleges { get; set; }
        public bool? Alairta { get; set; }

        [AllowHtml]
        public string Indoklas { get; set; }

    }
}
