//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class SzembesitesiJegyzokonyvModel
    {

        public List<int> FegyelmiUgyIds { get; set; }
        public List<int> SzembesitettFogvatartottIds { get; set; }
        public List<string> TovabbiSzemelyekList { get; set; }
        public string JegyzokonyvVezetoSid { get; set; }
        public string MeghallgatoSid { get; set; }
        public bool AlairtaFl { get; set; }

        public List<KSelect2ItemModel> JegyzokonyvVezetoOptions { get; set; }
        public List<KSelect2ItemModel> TovabbiSzemelyekOptions { get; set; }
        public List<KSelect2ItemModel> SzembesitettFogvatartottOptions { get; set; }
        public List<KSelect2ItemModel> MeghallgatoOptions { get; set; }        

        [AllowHtml]
        public string Leiras { get; set; }
        public List<int> NaplobejegyzesIds { get; set; }

    }
}
