//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edis.ViewModels.JFK.FENY
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Edis.Utilities;
    using Edis.ViewModels.Base;
    using System.ComponentModel.DataAnnotations;
    using Edis.Entities.JFK.FENY;
    using System.Web.Mvc;
    using System.Web.Helpers;
    using Newtonsoft.Json.Linq;
    using Edis.ViewModels.Common;

    public class VedoTelefonosTajekoztatasaModel
    {
        public List<int> FegyelmiUgyIds { get; set; }
        public List<int> NaplobejegyzesIds { get; set; }

        public List<KSelect2ItemModel> TajekoztatastNyujtoOptions { get; set; }

        [Required(ErrorMessage = "Tájékoztatást nyújtó mezõ megadása kötelezõ")]
        public string TajekoztatastNyujto { get; set; }
        
        [Required(ErrorMessage = "Tájékoztatott mezõ megadása kötelezõ")]
        [MaxLength(100)]
        public string Tajekoztatott { get; set; }  
        
        [Required(ErrorMessage = "Telefonszám megadása kötelezõ")]
        [MaxLength(100)]
        public string Telefonszam { get; set; }

        [Required(ErrorMessage = "Tájékoztatás idejének megadása kötelezõ")]
        public DateTime TajekoztatasIdeje { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Telefonszám megadása kötelezõ")]
        public string Leiras { get; set; }

        public string TajekoztatasSikertelensegenekOka { get; set; }

        public bool IsRogzites { get; set; }
    }
}
