import { registerComponent } from '../utils/vueUtils';

import DataTable from './tables/DataTable.vue';
registerComponent(DataTable);
import EsemenyekTable from './tables/EsemenyekTable.vue';
registerComponent(EsemenyekTable);
import IktatottNyomtatvanyokTable from './tables/IktatottNyomtatvanyokTable.vue';
registerComponent(IktatottNyomtatvanyokTable);
import SlidePanelWithFogvatartottAdatok from './layout/SlidePanelWithFogvatartottAdatok.vue';
registerComponent(SlidePanelWithFogvatartottAdatok);
import SlidePanelWithFejlec from './layout/SlidePanelWithFejlec.vue';
registerComponent(SlidePanelWithFejlec);
import SlidePanelEsemeny from './layout/SlidePanelEsemeny.vue';
registerComponent(SlidePanelEsemeny);
import SlidePanelEsemenyReszletek from './layout/SlidePanelEsemenyReszletek.vue';
registerComponent(SlidePanelEsemenyReszletek);
import SlidePanelFegyelmiUgyReszletek from './layout/SlidePanelFegyelmiUgyReszletek.vue';
registerComponent(SlidePanelFegyelmiUgyReszletek);
import SlidePanelJutalmiUgyReszletek from './layout/SlidePanelJutalmiUgyReszletek.vue';
registerComponent(SlidePanelJutalmiUgyReszletek);
import FegyelmiStatisztika from './layout/FegyelmiStatisztika.vue';
registerComponent(FegyelmiStatisztika);
import JutalmiStatisztika from './layout/JutalmiStatisztika.vue';
registerComponent(JutalmiStatisztika);
import LiveTimestamp from './controls/LiveTimestamp.vue';
registerComponent(LiveTimestamp);
import AnimatedNumber from './controls/AnimatedNumber.vue';
registerComponent(AnimatedNumber);
import FileUpload from './controls/FileUpload.vue';
registerComponent(FileUpload);
import Select2 from './controls/Select2.vue';
registerComponent(Select2);
import Select2Ajax from './controls/Select2Ajax.vue';
registerComponent(Select2Ajax);
import NyomtatottDokumentumok from './modals/NyomtatottDokumentumok.vue';
registerComponent(NyomtatottDokumentumok);
import BaseModal from './modals/BaseModal.vue';
registerComponent(BaseModal);
registerComponent(JutalomUgyekTable);
import JutalomUgyekTable from './tables/JutalomUgyekTable.vue';

import FegyelmiUgyElrendeles from './modals/FegyelmiUgyElrendeles.vue';
registerComponent(FegyelmiUgyElrendeles);
import ValaszhatoDokumentumok from './modals/ValaszhatoDokumentumok.vue';
registerComponent(ValaszhatoDokumentumok);
import EsemenyRogzites from './modals/EsemenyRogzites.vue';
registerComponent(EsemenyRogzites);
import ValaszhatoVedoDokumentumok from './modals/ValaszhatoVedoDokumentumok.vue';
registerComponent(ValaszhatoVedoDokumentumok);
import ReintegraciosTisztDonteseVisszakuldes from './modals/ReintegraciosTisztDonteseVisszakuldes.vue';
registerComponent(ReintegraciosTisztDonteseVisszakuldes);
import N2020Toolbar from './controls/N2020Toolbar.vue';
registerComponent(N2020Toolbar);
import FogvatartottKep from './controls/FogvatartottKep.vue';
registerComponent(FogvatartottKep);
import Summernote from './controls/Summernote.vue';
registerComponent(Summernote);
import VuelidateErrorExtractor from './controls/VuelidateErrorExtractor.vue';
registerComponent(VuelidateErrorExtractor);
import EsemenyResztvevo from './controls/EsemenyResztvevo.vue';
registerComponent(EsemenyResztvevo);
import JegyzokonyvTanuMeghallgatas from './modals/JegyzokonyvTanuMeghallgatas.vue';
registerComponent(JegyzokonyvTanuMeghallgatas);
import JegyzokonyvSzememelyiAllomanyiTanuMeghallgatas from './modals/JegyzokonyvSzememelyiAllomanyiTanuMeghallgatas.vue';
registerComponent(JegyzokonyvSzememelyiAllomanyiTanuMeghallgatas);
import OsszefoglaloJelentes from './modals/OsszefoglaloJelentes.vue';
registerComponent(OsszefoglaloJelentes);
import EljarasLefolytatasanakMegtagadasa from './modals/EljarasLefolytatasanakMegtagadasa.vue';
registerComponent(EljarasLefolytatasanakMegtagadasa);
import HelysziniSzemle from './modals/HelysziniSzemle.vue';
registerComponent(HelysziniSzemle);
import SzakteruletiVelemeny from './modals/SzakteruletiVelemeny.vue';
registerComponent(SzakteruletiVelemeny);
import FegyelmiUgyOsszevonas from './modals/FegyelmiUgyOsszevonas.vue';
registerComponent(FegyelmiUgyOsszevonas);
import ElsoFokuFegyelmiTargyalasElokeszitese from './modals/ElsoFokuFegyelmiTargyalasElokeszitese.vue';
registerComponent(ElsoFokuFegyelmiTargyalasElokeszitese);
import ElsoFokuTargyalasiJegyzokonyv from './modals/ElsoFokuTargyalasiJegyzokonyv.vue';
registerComponent(ElsoFokuTargyalasiJegyzokonyv);
import HatarozatRogzitese from './modals/HatarozatRogzitese.vue';
registerComponent(HatarozatRogzitese);
import BasicLoader from './controls/BasicLoader.vue';
registerComponent(BasicLoader);
import LiveHatarido from './controls/LiveHatarido.vue';
registerComponent(LiveHatarido);
import SzuroBadgek from './controls/SzuroBadgek.vue';
registerComponent(SzuroBadgek);
import SzuroBadgekGrouped from './controls/SzuroBadgekGrouped.vue';
registerComponent(SzuroBadgekGrouped);
import Ckeditor from './controls/Ckeditor.vue';
registerComponent(Ckeditor);

import './layout/naplobejegyzesek/_index';
import './modals/_index';
